2019-10-16 21:47:02,089 INFO: Microblog startup [in /Users/mikailkaya/Desktop/microblog/app/__init__.py:43]
2019-10-21 17:54:08,063 INFO: Microblog startup [in /Users/mikailkaya/Desktop/microblog/app/__init__.py:43]
2019-10-21 18:07:22,087 INFO: Microblog startup [in /Users/mikailkaya/Desktop/microblog/app/__init__.py:43]
2019-10-21 18:11:06,591 INFO: Microblog startup [in /Users/mikailkaya/Desktop/microblog/app/__init__.py:43]
2019-10-21 18:12:30,232 INFO: Microblog startup [in /Users/mikailkaya/Desktop/microblog/app/__init__.py:43]
2019-10-21 18:16:02,037 INFO: Microblog startup [in /Users/mikailkaya/Desktop/microblog/app/__init__.py:43]
2019-10-21 18:16:52,694 INFO: Microblog startup [in /Users/mikailkaya/Desktop/microblog/app/__init__.py:43]
2019-10-21 18:17:53,485 INFO: Microblog startup [in /Users/mikailkaya/Desktop/microblog/app/__init__.py:43]
2019-10-21 18:18:19,619 INFO: Microblog startup [in /Users/mikailkaya/Desktop/microblog/app/__init__.py:43]
2019-10-21 18:18:33,055 INFO: Microblog startup [in /Users/mikailkaya/Desktop/microblog/app/__init__.py:43]
2019-10-21 18:19:01,870 INFO: Microblog startup [in /Users/mikailkaya/Desktop/microblog/app/__init__.py:43]
2019-10-21 18:19:14,386 INFO: Microblog startup [in /Users/mikailkaya/Desktop/microblog/app/__init__.py:43]
2019-10-21 18:21:53,120 INFO: Microblog startup [in /Users/mikailkaya/Desktop/microblog/app/__init__.py:43]
2019-10-21 18:23:56,227 INFO: Microblog startup [in /Users/mikailkaya/Desktop/microblog/app/__init__.py:43]
2019-10-21 18:32:29,560 INFO: Microblog startup [in /Users/mikailkaya/Desktop/microblog/app/__init__.py:43]
2019-10-21 18:33:27,912 INFO: Microblog startup [in /Users/mikailkaya/Desktop/microblog/app/__init__.py:43]
2019-10-21 18:34:27,067 INFO: Microblog startup [in /Users/mikailkaya/Desktop/microblog/app/__init__.py:43]
2019-10-21 18:34:56,141 INFO: Microblog startup [in /Users/mikailkaya/Desktop/microblog/app/__init__.py:43]
2019-10-21 18:35:30,501 INFO: Microblog startup [in /Users/mikailkaya/Desktop/microblog/app/__init__.py:43]
2019-10-21 18:35:47,021 INFO: Microblog startup [in /Users/mikailkaya/Desktop/microblog/app/__init__.py:43]
2019-10-21 18:36:33,697 INFO: Microblog startup [in /Users/mikailkaya/Desktop/microblog/app/__init__.py:43]
2019-10-21 18:39:47,032 INFO: Microblog startup [in /Users/mikailkaya/Desktop/microblog/app/__init__.py:43]
2019-10-21 18:42:32,619 INFO: Microblog startup [in /Users/mikailkaya/Desktop/microblog/app/__init__.py:43]
2019-10-21 19:04:27,616 INFO: Microblog startup [in /Users/mikailkaya/Desktop/microblog/app/__init__.py:43]
2019-10-21 19:06:05,826 INFO: Microblog startup [in /Users/mikailkaya/Desktop/microblog/app/__init__.py:43]
2019-10-21 20:34:25,379 INFO: Microblog startup [in /Users/mikailkaya/Desktop/microblog/app/__init__.py:43]
2019-10-21 20:35:54,485 ERROR: Exception on /register [POST] [in /Users/mikailkaya/Desktop/microblog/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/mikailkaya/Desktop/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mikailkaya/Desktop/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mikailkaya/Desktop/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mikailkaya/Desktop/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/mikailkaya/Desktop/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mikailkaya/Desktop/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/mikailkaya/Desktop/microblog/app/routes.py", line 65, in register
    user.set_password(form.password.data)
AttributeError: 'User' object has no attribute 'set_password'
2019-10-21 20:46:19,024 INFO: Microblog startup [in /Users/mikailkaya/Desktop/microblog/app/__init__.py:43]
2019-10-23 20:49:14,619 ERROR: Exception on /register [POST] [in /Users/mikailkaya/Desktop/microblog/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/mikailkaya/Desktop/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mikailkaya/Desktop/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mikailkaya/Desktop/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mikailkaya/Desktop/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/mikailkaya/Desktop/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mikailkaya/Desktop/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/mikailkaya/Desktop/microblog/app/routes.py", line 65, in register
    user.set_password(form.password.data)
AttributeError: 'User' object has no attribute 'set_password'
2019-10-23 20:50:14,165 ERROR: Exception on /register [POST] [in /Users/mikailkaya/Desktop/microblog/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/mikailkaya/Desktop/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mikailkaya/Desktop/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mikailkaya/Desktop/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mikailkaya/Desktop/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/mikailkaya/Desktop/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mikailkaya/Desktop/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/mikailkaya/Desktop/microblog/app/routes.py", line 65, in register
    user.set_password(form.password.data)
AttributeError: 'User' object has no attribute 'set_password'
